### PR TITLE
make it easy to run everythin that travis would do

### PR DESCRIPTION
**Pull request by grosser**
@williammartin later a nice place to add more stuff too :)

### CODE REVIEW

**Comment by williammartin** [comment]
I'm pro Makefiles, but I'd like to get some thoughts from other developers before merging this.

**Comment by grosser** [comment]
already 2 weeks old, so doubt anyone will show up ... want to ping whoever can review this ?

**Comment by williammartin** [comment]
Yes I pinged some people internally, but @nodo @blgm here

**Comment by williammartin** [comment]
Alright I'm convinced. Merging. Thanks for the contribution.

**Pull request merged**
