### PR TITLE
Gomega yaml matcher

### PR DESCRIPTION
**Pull request by mariantalla**
As discussed in #139 , we are submitting the code for the gomega YAML matcher.

### CODE REVIEW

**Comment by robdimsdale** [comment]
I think this looks ok, but I'd like to give @onsi the opportunity to chime in on the topic of using the `extensions` package for matchers with third-party dependencies?

Given a similar situation in https://github.com/onsi/ginkgo/pull/239 and the fact we have already established a pattern in this repo for [copying in dependencies like goraph](https://github.com/onsi/gomega/tree/master/matchers/support/goraph) we may yet decide to go down an alternate route.

**Comment by tinygrasshopper** [comment]
@onsi any thoughts on this PR?

**Comment by rosenhouse** [comment]
@robdimsdale @tinygrasshopper  Surprised to see this merged:

- The go-yaml dependency has a non-standard license, which has unresolved legal issues for Pivotal.

- The Release Infrastructure team built [their own yaml matcher](https://github.com/pivotal-cf-experimental/gomegamatchers) but was under the impression at the time that @onsi wasn't interested in getting a PR for gomega, due to the extra required dependency.

cc: @Amit-PivotalLabs @zankich

**Comment by robdimsdale** [comment]
Sorry for the confusion here.

I can't speak to the first issue, but we've been using that library throughout Pivotal projects for months - personally I was under the impression it's either been cleared, or else it's not a problem.

As to the second, we didn't want to merge a matcher because we (incorrectly) thought it would cause more breakages along the lines of the protobuf transitive dependencies - this was recently disproved by the london team.

If we have a better yaml matcher we should look at improving this one - either way, consolidation would be great.

**Pull request merged**
