### PR TITLE
Adding code to run on Powersystem

### PR DESCRIPTION
**Pull request by genisysram**
Hi
Here is my contribution to your code, its working good on powersystems.

Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

### CODE REVIEW

**Comment by williammartin** [comment]
Hi @genisysram thanks for your contribution.

I don't think we make any guarantees of supporting gomega on power pc right now, but it's something we could look into. I see that you're working on behalf of IBM, are they looking for support?

**Comment by genisysram** [comment]
I'm working on behalf of IBM, they will support power system.

**Comment by williammartin** [comment]
@genisysram we can merge this so that IBM has confidence that gomega currently works on PowerPC but I suspect it's unlikely that any of the current maintainers will do anything if the tests break unless we see real usage.

**Comment by genisysram** [comment]
we will look in future how it goes ,if code breaks , but merge as of now , such that we can say that the code will work on powersystems

**Pull request merged**
