### PR TITLE
feat: add Compare using go-cmp

### PR DESCRIPTION
**Pull request by xiantank**
Add new matcher `Compare`, which use go-cmp to compare and we can pass cmp.Option as optional arguments.
here is example
```go
Expect([]int{1, 2}).Should(Compare([]int{1, 2}))
Expect(myCustomType{s: "foo", n: 3, f: 2.0, arr: []string{"a", "b"}}).Should(Compare(myCustomType{s: "foo", n: 3, f: 2.0, arr: []string{"a", "b"}}, cmp.AllowUnexported(myCustomType{})))
Expect(myCustomType{s: "abc", n: 3, f: 2.0, arr: []string{"a", "b"}}).Should(Compare(myCustomType{s: "foo", n: 3, f: 2.0, arr: []string{"a", "b"}}, cmpopts.IgnoreUnexported(myCustomType{})))
```

related: #216, #264

### CODE REVIEW

**Comment by thediveo** [comment]
Just my tiny observation as I happened to look at go-cmp just these days (while working on checking file descriptor objects for equality). I remember that go-cmp thankfully documents its purposedly designed behavior of `panic`king, because it is intended to work without any matcher framework. It cannot rely on the usual error handling pattern that the Gomega matchers uses: matchers do not only return their "verdict" but also an error return value. I would, erm, expect that without handling panics the Compare matcher cannot be used in inverse expectations such as `Expect(foo).NotTo(Compare())`. If I didn't overlook something in your PR code (and please forgive me if I do and correct me please) then there's a inverse check using `Equal` but not one using `Compare`?

**Comment by xiantank** [comment]
Hi, I add some panic handling to make Compare matcher as usual error handling pattern, and remove a weird inverse check Equal (which I tried to show difference between `Equal` and `Compare` deal with different time location, but it's really weird to do so, thanks for pointing it out).
// please let me know if I misunderstood anything

**Comment by onsi** [comment]
hey @xiantank - can we rename it to `BeComparableTo`?  That would flow better for the DSL `Expect(foo).To(BeComparableTo(bar))`

I think I'd, eventually, like to make it possible to configure Gomega so that `Equal` can be backed by `go-cmp` instead of `reflect.DeepEqual`.  This is a great step in that direction, thanks!

**Comment by onsi** [comment]
thanks! looks good to me!

**Comment by onsi** [comment]
if you want to update the doc PR I can pull that in too

**Pull request merged**
