### PR TITLE
Makes xml attributes comparison work for go < 1.8

### PR DESCRIPTION
**Pull request by aubm**

### CODE REVIEW

**Comment by onsi** [comment]
Hmm.. looks like pulling in the unicode PR broke this one.  Mind fixing it @aubm ?

**Comment by aubm** [comment]
No problem, it should be ok :)

**Comment by aubm** [comment]
And thank you for maintaining this package by the way, I use it in my day-to-day work and I really enjoy it!

**Comment by onsi** [comment]
Glad you're finding it useful!

**Pull request merged**
