### PR TITLE
Implement `PanicWith()`.

### LINKED ISSUE #257: Panic matcher for a specific value.
Is there an existing way to assert that a function panics with a specific value? I've had a look through the docs and source and couldn't see anything.

If not, would a PR for such a feature be welcome?

I'm picturing usage something like:

```go
Expect(fn).To(PanicWith(Equal(expected)))
```

I've put together a [quick and dirty prototype](https://gist.github.com/jmalloc/73882599fa705b8d098b9bcdf4544bc5) which works but the failure messages are not particularly great.

### PR DESCRIPTION
**Pull request by jmalloc**
Fixes #257 

I finally got around to making an attempt at `PanicWith()` as discussed in the aforementioned issue which I opened quite some time ago.

I've stuck with the name `PanicWith()` as we didn't manage to come up with anything better in the issue when it was last discussed.

### CODE REVIEW

**Comment by jmalloc** [comment]
Please see #382 for documentation changes.

**Comment by jmalloc** [comment]
Please note that the CI failure was only for Go v1.12, I don't believe it to be related to these changes.

**Comment by jmalloc** [comment]
I've updated this PR to produce more description failure messages when a panic does occur, but not with the expected value.

**Comment by DblK** [comment]
Any idea about the next step for this PR?

**Comment by williammartin** [comment]
@DblK yep yep, I am hopefully going to find time to review it today. Thanks for the bump, I lose track of things so easily these days :)

**Comment by williammartin** [comment]
Looks great to me. Don't mind the 1.12 failure, something orthogonal. Thanks!

**Comment by jmalloc** [comment]
Happy to finally contribute! Would I be out of line asking when this might make it into a tag? 😄

**Comment by williammartin** [comment]
OUT OF ORDER! We'll have to check out the 1.12 failure before doing a release but otherwise asap.

**Comment by williammartin** [comment]
This has been released in [v1.10.0](https://github.com/onsi/gomega/releases/tag/v1.10.0), thanks for your contribution @jmalloc

**Comment by jmalloc** [comment]
Excellent, thank you!

**Pull request merged**
